### ISSUE TITLE
Are emitters u equal to map exit (portals u)?

### ISSUE THREAD

**Issue by Bodigrim** [cdupont/timetravel#1]
https://github.com/cdupont/Timeloop/blob/431ff4de38838252a7ae20ded0492e850511eb47/src/TimeLoop/Types.hs#L52-L56

Does it hold that `emitters u == map exit (portals u)`? Or could they be out of sync?

**Comment by cdupont** [comment]
No, emitters are standalone sources of walkers. An emitter will "emit" a walker at a specific time, without condition.
A portal exit will also emit a walker, on the condition that a walker enters the entry portal at the right time.

In practice, I put some emitters on the map so that walkers are already there at the beginning of the simulation.

**Comment by Bodigrim** [comment]
Thanks! Nice project, I enjoyed reading the code.

**Comment by cdupont** [comment]
Thanks :)
